# Generated by Django 6.0 on 2026-01-13 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('bounds_x', models.FloatField(default=200.0)),
                ('bounds_y', models.FloatField(default=50.0)),
                ('bounds_z', models.FloatField(default=160.0)),
            ],
        ),
        migrations.CreateModel(
            name='StorageBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_code', models.CharField(max_length=50)),
                ('row', models.IntegerField(default=0)),
                ('shelf', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('width', models.FloatField(default=1.2)),
                ('height', models.FloatField(default=0.7)),
                ('depth', models.FloatField(default=1.2)),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='api.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.IntegerField(default=6)),
                ('racks_per_row', models.IntegerField(default=8)),
                ('max_levels', models.IntegerField(default=4)),
                ('rack_type', models.CharField(choices=[('basic', 'Basic'), ('pallet', 'Pallet')], default='basic', max_length=20)),
                ('rack_width', models.FloatField(default=4.0)),
                ('rack_depth', models.FloatField(default=2.0)),
                ('shelf_gap', models.FloatField(default=2.0)),
                ('bin_width', models.FloatField(default=1.2)),
                ('bin_height', models.FloatField(default=0.7)),
                ('bin_depth', models.FloatField(default=1.2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='api.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BinSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_code', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('depth', models.FloatField()),
                ('row', models.IntegerField()),
                ('shelf', models.IntegerField()),
                ('level', models.IntegerField()),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('abc', models.CharField(default='C', max_length=1)),
                ('hits', models.IntegerField(default=0)),
                ('qty', models.FloatField(default=0.0)),
                ('utilization', models.FloatField(default=0.0)),
                ('occupied', models.BooleanField(default=False)),
                ('over_capacity', models.BooleanField(default=False)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bin_snapshots', to='api.warehousesnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='BinStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.FloatField(default=0.0)),
                ('uom', models.CharField(default='EA', max_length=10)),
                ('abc_class', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='C', max_length=1)),
                ('hit_count', models.IntegerField(default=0)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.storagebin')),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='api_binstoc_product_886d76_idx'), models.Index(fields=['abc_class'], name='api_binstoc_abc_cla_3c94eb_idx')],
                'unique_together': {('bin', 'product', 'batch')},
            },
        ),
        migrations.AddIndex(
            model_name='storagebin',
            index=models.Index(fields=['warehouse', 'bin_code'], name='api_storage_warehou_12bd47_idx'),
        ),
        migrations.AddIndex(
            model_name='storagebin',
            index=models.Index(fields=['zone'], name='api_storage_zone_b28bde_idx'),
        ),
        migrations.AddIndex(
            model_name='storagebin',
            index=models.Index(fields=['row', 'shelf', 'level'], name='api_storage_row_dd259b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storagebin',
            unique_together={('warehouse', 'bin_code')},
        ),
        migrations.AlterUniqueTogether(
            name='warehousesnapshot',
            unique_together={('warehouse', 'version')},
        ),
        migrations.AddIndex(
            model_name='binsnapshot',
            index=models.Index(fields=['bin_code'], name='api_binsnap_bin_cod_1392b6_idx'),
        ),
        migrations.AddIndex(
            model_name='binsnapshot',
            index=models.Index(fields=['zone'], name='api_binsnap_zone_ac83c9_idx'),
        ),
    ]
