# Generated by Django 6.0 on 2026-01-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='storagebin',
            name='api_storage_warehou_12bd47_idx',
        ),
        migrations.RemoveIndex(
            model_name='storagebin',
            name='api_storage_zone_b28bde_idx',
        ),
        migrations.RemoveIndex(
            model_name='storagebin',
            name='api_storage_row_dd259b_idx',
        ),
        migrations.AddField(
            model_name='storagebin',
            name='abc_class',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], db_index=True, default='C', max_length=1),
        ),
    ]
