# Generated by Django 6.0 on 2026-01-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_storagebin_api_storage_warehou_12bd47_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='storagebin',
            index=models.Index(fields=['warehouse', 'bin_code'], name='api_storage_warehou_12bd47_idx'),
        ),
        migrations.AddIndex(
            model_name='storagebin',
            index=models.Index(fields=['zone'], name='api_storage_zone_b28bde_idx'),
        ),
        migrations.AddIndex(
            model_name='storagebin',
            index=models.Index(fields=['row', 'shelf', 'level'], name='api_storage_row_dd259b_idx'),
        ),
    ]
