# Generated by Django 6.0 on 2026-01-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_storagebin_api_storage_warehou_12bd47_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagebin',
            name='height',
            field=models.FloatField(default=1.2),
        ),
    ]
