# Generated by Django 6.0 on 2026-01-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_storagebin_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseconfig',
            name='bin_height',
            field=models.FloatField(default=1.2),
        ),
    ]
